### ISSUE TITLE
初始化错误问题

### ISSUE THREAD

**Issue by 93xiaoliumang** [HsuanXyz/ionic2-city-picker#10]
我想把这个用在收获地址那边，但是发现。 假如我有地址的时候， 比如“福建省 - 厦门市 - 湖里区” ， 然后不会初始化到打开的小模态框中， 看了下你的代码 ，发现是不是在 validate时， 没赋初始值，然后导致初始化不成功
![8 b g1 g oc h ik ca3](https://cloud.githubusercontent.com/assets/28618616/26525061/5b5ba036-437d-11e7-8b1f-267dd94ff702.png)

**Comment by 93xiaoliumang** [comment]
当我有初始值， “福建省 - 厦门市 - 湖里区” 时，点进去，第一个if判断 当前this.provinceCol 肯定不等于 provinceCol.selectedIndex， 所以就把市区的cityCol.selectedIndex  置为0了。 然后每次打开面板就只有省有，市和区都是没有选择的

**Comment by hsuanxyz** [comment]
感谢你的issues，我尝试修复

**Comment by hsuanxyz** [comment]
如你所述，在 `generate` 函数里没有将初始化的索引存入临时变量，导致在允许`validate `函数时，错误的将其当作一次新的切换动作，将市区设置索引设置为0。
现在你可以更新版本决绝这个问题。再次感谢你的issues

``` bash
npm i ionic2-city-picker@0.0.11 --save
```

**Comment by 93xiaoliumang** [comment]
感谢，已更新，马上尝试一下
