### ISSUE TITLE
请问如何初始化选中默认值.

### ISSUE THREAD

**Issue by xiaosan666** [HsuanXyz/ionic2-city-picker#13]
如默认cityName="广东省-广州市-天河区".第一次打开CityPicker如何选中广东省-广州市-天河区

**Comment by hsuanxyz** [comment]
用你设置的分隔符连接字符串就可以了。

**Comment by yanxiaojun617** [comment]
可以了.之前不行的原因是:
你demo里的分隔符前后各有一个空格,而我赋值给cityName没有空格
`<city-picker item-content
                 [cancelText]="'取消'"
                 [doneText]="'完成'"
                 [separator]="' - '"
                 [citiesData]="cityData"
                 [(ngModel)]="cityName"
                 (ionChange)="cityChange($event)">

    </city-picker>`
而你的cityName没有使用分隔符
`cityName:string = '北京市 北京市 东城区'; //初始化城市名`
建议你完善一下这段代码.让直接copy就能用哈.

**Comment by xiaosan666** [comment]
可以了.之前不行的原因是:
你demo里的分隔符前后各有一个空格,而我赋值给cityName没有空格
`[separator]="' - '"`
而你的cityName没有使用分隔符
`cityName:string = '北京市 北京市 东城区'; //初始化城市名`
建议你完善一下这段代码.让直接copy就能用哈.

**Comment by hsuanxyz** [comment]
已经修复了文档错误，谢谢指出。
我现在要关闭这个问题。

**Comment by xiaosan666** [comment]
关吧
