### ISSUE TITLE
在ionic3.0的版本好像用不了了啊,?

### ISSUE THREAD

**Issue by Swing-Ming** [HsuanXyz/ionic2-city-picker#2]

**Comment by w13159584927** [comment]
我这个到3.0也报错了。

**Comment by hsuanxyz** [comment]
@Swing-Ming 
@w13159584927 
是的，3.0导致很多第三发组件无法使用，因为它模块加载的方式发生了变化，我正在寻找兼容方式，如果3.0没有可以向下兼容的方式，我会发布一个3.0分支来给3.0提供支持

**Comment by Swing-Ming** [comment]
恩恩,好的,谢了

**Comment by hsuanxyz** [comment]
@Swing-Ming  你好，我在尝试解决问题的时候发现不光是模块带来不兼容，一些方法上的官方也做了变更，为了很好的保证下个版本的兼容性，你是否可以将你的报错信息贴出来，以便我做跟全面的升级。谢谢

**Comment by hsuanxyz** [comment]
@Swing-Ming @w13159584927 
我已经修复了问题，请更新版本

**Comment by renyuns** [comment]
@HsuanXyz 您好,npm install的时候,出现这个?这是我的系统不支持吗?
![e d i_k zyhwz ukizxuow](https://cloud.githubusercontent.com/assets/22095724/24848167/24dbf9ca-1df8-11e7-9b07-671e9a8f8be3.png)
然后运行的时候出现这
![k ww 8 r0g1xr k c 6dxb](https://cloud.githubusercontent.com/assets/22095724/24848468/7a6f19e8-1df9-11e7-9043-146185d72027.png)

**Comment by hsuanxyz** [comment]
@renyuns  你有在app.module.ts 文件引入 CityPickerModule 吗？
如果引入了还是得到此错误，请你将你的相关的代码，以及ionic版本贴上来

**Comment by renyuns** [comment]
ionic版本
![7 9zho a7690uz70 s_nm](https://cloud.githubusercontent.com/assets/22095724/24850603/503a0ca0-1e03-11e7-8cdc-1ee624205e74.png)
文件目录
![mulu](https://cloud.githubusercontent.com/assets/22095724/24850623/5c5a1d7c-1e03-11e7-95c2-7b1538bfbd3f.png)
app.module.ts
![app module](https://cloud.githomubusercontent.com/assets/22095724/24850640/6c77dfa0-1e03-11e7-8172-d938b096a80c.png)
app.module.ts
![app module](https://cloud.githubusercontent.com/assets/22095724/24850652/7c8bee0e-1e03-11e7-951a-ee8465b8cdb2.png)
city-picker服务
![fuwu](https://cloud.githubusercontent.com/assets/22095724/24850671/8e104fee-1e03-11e7-8277-0b874345232d.png)
home.ts
![ts](https://cloud.githubusercontent.com/assets/22095724/24850681/99cadb88-1e03-11e7-8b55-8d55bd1e0338.png)
home.html
![htmln3w h](https://cloud.githubusercontent.com/assets/22095724/24850695/a5aaca76-1e03-11e7-95d1-d0c901ac76b1.png)

**Comment by renyuns** [comment]
@HsuanXyz app.module.ts
![app module](https://cloud.githubusercontent.com/assets/22095724/24850724/c05e3de4-1e03-11e7-9ed9-118c79de2fa0.png)

**Comment by hsuanxyz** [comment]
@renyuns 这也许是v3组件懒加载造成的错误，你可以尝试将 CityPickerModule 在home.module.ts 引入试试。我有空的时候会做尝试，如果你成功了记得告诉我！

**Comment by w13159584927** [comment]
用是能用了，不过在mac环境下，浏览器打开和打成ios包都可以，打android包的时候，用 ionic build android --prod 这个命令就会报错，错误信息如下：Error: Template parse errors: Can't bind to 'cancelText' since it isn't a known property of 'city-picker'. 
            1. If 'city-picker' is an Angular component and it has 'cancelText' input, then verify that it is part of 
            this module. 2. If 'city-picker' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the 
            '@NgModule.schemas' of this component to suppress this message. 3. To allow any property add 
            'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. (" <city-picker item-content [ERROR 
            ->][cancelText]="'取消'" [doneText]="'完成'" [separator]="' - '" "): 
            ng:///Users/wangjinghui/Desktop/association/src/pages/open-shop/open-shop.html@47:17 Can't bind to 
            'doneText' since it isn't a known property of 'city-picker'. 1. If 'city-picker' is an Angular component and 
            it has 'doneText' input, then verify that it is part of this module. 2. If 'city-picker' is a Web Component 
            then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. 3. 
            To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. (" <city-picker 
            item-content [cancelText]="'取消'" [ERROR ->][doneText]="'完成'" [separator]="' - '" [citiesData]="cityData" "): 
            ng:///Users/wangjinghui/Desktop/association/src/pages/open-shop/open-shop.html@48:17 Can't bind to 
            'separator' since it isn't a known property of 'city-picker'. 1. If 'city-picker' is an Angular component 
            and it has 'separator' input, then verify that it is part of this module. 2. If 'city-picker' is a Web 
            Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this 
            message. 3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. (" 
            [cancelText]="'取消'" [doneText]="'完成'" [ERROR ->][separator]="' - '" [citiesData]="cityData" 
            [(ngModel)]="cityName" "): 
            ng:///Users/wangjinghui/Desktop/association/src/pages/open-shop/open-shop.html@49:17

**Comment by hsuanxyz** [comment]
@renyuns 我开了一个新issues (#3)
