### ISSUE TITLE
ionic3.0 有问题啊 

### ISSUE THREAD

**Issue by YouSirY** [HsuanXyz/ionic2-city-picker#5]
BrowserModule has already been loaded. If you need access to common directives such as NgIf and NgFor from a lazy loaded module, import CommonModule instead.

**Comment by YouSirY** [comment]
ionic3 lazyload 在APP Module里面import  在子component里调用 报错找不到city-picker
然后改成 在子module调用 直接报上面那个错误

**Comment by hsuanxyz** [comment]
@YouSirY 嗨，我得到了这个错误。我现在可以修复，不过我还需要确认一下改动是否会影响低版本。

**Comment by hsuanxyz** [comment]
@YouSirY  你好，你现在可以使用新版本 `npm install ionic2-city-picker@0.0.7 --save`
