### ISSUE TITLE
ionic 3.0 多切换几次城市报错

### ISSUE THREAD

**Issue by YouSirY** [HsuanXyz/ionic2-city-picker#6]
Runtime Error
undefined is not an object (evaluating 'opt._dur')

**Comment by hsuanxyz** [comment]
@YouSirY 
谢谢，我将尝试重现问题。
可以的话我需要你告诉我以下信息：
1. 在项目目录下执行 `ionic info`命令获取开发环境。
2. package.json 中 devDependencies与dependencies字段内容。

这项会为我重现和修复问题提供很大的帮助。

**Comment by Lsy-kg** [comment]
我也遇到了同样的问题 @HsuanXyz   Uncaught TypeError:  Cannot read property '_dur' of undefined
我的ionic info:
ordova CLI: 6.5.0
Ionic Framework Version: 3.0.1
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v7.2.0
Xcode version: Not installed

package.json:
"dependencies": {
    "@angular/common": "4.0.0",
    "@angular/compiler": "4.0.0",
    "@angular/compiler-cli": "4.0.0",
    "@angular/core": "4.0.0",
    "@angular/forms": "4.0.0",
    "@angular/http": "4.0.0",
    "@angular/platform-browser": "4.0.0",
    "@angular/platform-browser-dynamic": "4.0.0",
    "@ionic-native/core": "3.4.2",
    "@ionic-native/splash-screen": "3.4.2",
    "@ionic-native/status-bar": "3.4.2",
    "@ionic/storage": "2.0.1",
    "ionic-angular": "3.0.1",
    "ionic2-city-picker": "0.0.7",
    "ionicons": "3.0.0",
    "rxjs": "5.1.1",
    "sw-toolbox": "3.4.0",
    "zone.js": "^0.8.4"
  },
  "devDependencies": {
    "@ionic/app-scripts": "1.3.0",
    "typescript": "~2.2.1"
  }

**Comment by YouSirY** [comment]
这个问题已经解决了 把refreash那句代码删除

**Comment by Lsy-kg** [comment]
@YouSirY 在哪里？没找到

**Comment by hsuanxyz** [comment]
package.json

```diff
  "dependencies": {
    ...
- "ionic2-city-picker": "0.0.7",
+ "ionic2-city-picker": "0.0.9",
    ...
  }
```

`npm install`
