### ISSUE TITLE
可以点击单个标签弹出吗

### ISSUE THREAD

**Issue by wangying11** [HsuanXyz/ionic2-city-picker#7]
您现在是点击整个面板都会弹出

**Comment by hsuanxyz** [comment]
不行，它继承的list-item

**Comment by wangying11** [comment]
可以改进一下吗

**Comment by wangying11** [comment]
如果那个页面有其他事件就没用了

**Comment by hsuanxyz** [comment]
的确会有这个问题，你可以把你真实的需求告诉我，我会尝试解决

**Comment by wangying11** [comment]
我就是要点击这个标签才弹出，点击其他地方不弹出

**Comment by jameschopin** [comment]
我现在将你的接口改造了 你的接口 必须是【省,children 然后底下一个child】 我这边的接口 是请求省 市 区 封到一个三维数组 结构跟你保持一致了 目前样式在手机上 滚动太快 会黑屏 请问有什么好的解决方案吗 滑的太快的原因导致的 我想的话

**Comment by vvu2014** [comment]
步骤：
1. 打开城市列表选择器，选择北京-北京-东城区，点击完成。
2.  再次打开城市列表选择器，拖动鼠标向上拉省级那一列（其他列如市级先别选择），比如省级选中天津，这是市级和区县级就会显示北京和东城区。

这个bug只是首次拖动鼠标选择省级才会出现，如果再一次拖动鼠标选择其他省级则一切ok。兄弟，有时间的话看能不能改哦。
