### ISSUE TITLE
选择省级后，市级和区县级没有跟着更新，只是第一次会出现这个问题

### ISSUE THREAD

**Issue by vvu2014** [HsuanXyz/ionic2-city-picker#9]
步骤：

打开城市列表选择器，选择北京-北京-东城区，点击完成。
再次打开城市列表选择器，拖动鼠标向上拉省级那一列（其他列如市级先别选择），比如省级选中天津，这时市级和区县级就会显示北京和东城区。
这个bug只是首次拖动鼠标选择省级才会出现，如果再一次拖动鼠标选择其他省级则一切ok。兄弟，有时间的话看能不能改哦。

**Comment by hsuanxyz** [comment]
```bash
npm i ionic2-city-picker@0.0.10 --save
```
